// Generated by CoffeeScript 1.9.2
(function() {
  var _;

  _ = require('lodash');

  module.exports = function(board) {
    return defineComponent({
      mixins: [board.mixin],
      render: function() {
        return dom.a(_.merge({}, this.props, {
          onClick: this.wire(function() {
            return this.cancel().set(this.props.href).to(this.board.path.navigate);
          })
        }));
      }
    });
  };

}).call(this);
