// Generated by CoffeeScript 1.9.2
(function() {
  var kefir;

  kefir = require('kefir');

  module.exports = {
    path: function(board) {
      return {
        signal: board.signal(document.location.pathname, kefir.fromEvents(window, 'popstate'), function() {
          return document.location.pathname;
        }, board.slot('path.navigate').filter(function(it) {
          return window.location.pathname !== it;
        }).doAction(function(path) {
          return window.history.pushState(null, null, path);
        })),
        navigate: board.slot('path.navigate')
      };
    }
  };

}).call(this);
