// Generated by CoffeeScript 1.9.2
(function() {
  var REACT_ELEMENTS, _, dom, react,
    slice = [].slice;

  react = require('react');

  _ = require('lodash');

  REACT_ELEMENTS = 'a abbr address area article aside audio b base bdi bdo big blockquote body br button canvas caption cite code col colgroup data datalist dd del details dfn dialog div dl dt em embed fieldset figcaption figure footer form h1 h2 h3 h4 h5 h6 head header hr html i iframe img input ins kbd keygen label legend li link main map mark menu menuitem meta meter nav noscript object ol optgroup option output p param picture pre progress q rp rt ruby s samp script section select small source span strong style sub summary sup table tbody td textarea tfoot th thead time title tr track u ul var video wbr';

  dom = {};

  REACT_ELEMENTS.split(' ').forEach(function(it) {
    return dom[it] = function() {
      var attr, children;
      attr = arguments[0], children = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      return react.createElement.apply(react, [it, attr].concat(slice.call(children)));
    };
  });

  module.exports = {
    dom: dom,
    h: function() {
      var children, classes, current, elem, name, props, ref, selector, selectors;
      selector = arguments[0], props = arguments[1], children = 3 <= arguments.length ? slice.call(arguments, 2) : [];
      if (props == null) {
        props = {};
      }
      selectors = selector.split(' ');
      if (!children.length) {
        children = void 0;
      }
      while (selectors.length) {
        ref = selectors.pop().split('.'), name = ref[0], classes = 2 <= ref.length ? slice.call(ref, 1) : [];
        name || (name = 'div');
        elem = dom[name];
        if (!elem) {
          throw new Error("undefined element " + name);
        }
        current = elem(_.merge({}, props, {
          children: children,
          className: classes.join(' ') + ((props != null ? props.className : void 0) && (' ' + (props != null ? props.className : void 0)) || '')
        }));
        children = current;
        props = {};
      }
      return current;
    },
    defineComponent: function(component) {
      return react.createFactory(react.createClass(component));
    }
  };

}).call(this);
